spring:
  datasource:
    url: jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres?user=postgres.mvuftpomwptrgzchyeoh&password=Hovno_Hori123&prepareThreshold=0&preferQueryMode=simple
    username: postgres
    password: Hovno_Hori123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        default_schema: public
        format_sql: true
  jackson:
    time-zone: UTC

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug